version: '3.7'

services:
  server:
    build:
      context: .
    ports:
      - "3500:3500"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecom
    networks:
      - ecom
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    networks:
      - ecom

  db:
    image: postgres:10.4-alpine
    container_name: ecom-postgres-db
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecom

volumes:
  db-data:

networks:
  ecom:
    driver: bridge
